---
title: "Analysis of Species"
author: "Scott White"
date: "April 8, 2019"
output: pdf_document
---

```{r}
library(here)
library(tidyverse)
library(Hmisc)
library(ggmosaic)
```

# Read in data
```{r}
bees <- read_csv(here("Assignments/Assignment3/data_output/cleaned_bees_columns_removed.csv"),
                 col_types = cols(Division = col_character()))
```

```{r}
bees <- bees %>% mutate(Month = as_factor(Month))
bees <- bees %>% mutate(Month = fct_relevel(Month, levels = c("May", "Jun", "Jul", "Aug", "Sept")))

bees <- bees %>% mutate(State = as_factor(State))
bees <- bees %>% mutate(State = fct_relevel(State, levels = c("Wisconsin", "Illinois", "Minnesota", "Iowa", "Missouri")))

bees
```

```{r}
apply(bees, 2, function(x) length(unique(x)))
```



```{r}
genus_counts <- bees %>% group_by(Genus) %>% summarise(Count = n()) %>%
  ggplot(aes(reorder(Genus, Count), Count)) +
  geom_col(fill = "#0099FF")  +
  geom_text(aes(label = Count, hjust = -0.1)) +
  coord_flip() +
  ggtitle("Number of sightings of each genus", "From May to September") +
  xlab("Genus") +
  ylim(c(0, 1800)) +
  theme(axis.title = element_text(size = 16),
        plot.title = element_text(size = 20))
genus_counts

# ggsave("genus_counts.png", genus_counts)
```

```{r}
bees %>% group_by(State, Month, Genus) %>% summarise(Count = n()) %>% drop_na() %>% 
  ggplot(aes(reorder(State, Count, FUN = function(x)sum(x)), Count)) +
  geom_col(aes(fill = Month))  +
  # geom_text(aes(label = Count, hjust = -0.1)) +
  coord_flip() +
  ggtitle("Count by state per month") +
  xlab("State") +
  ylim(c(0, 1800)) +
  theme(axis.title = element_text(size = 16),
        plot.title = element_text(size = 20))
```


```{r}
bees %>% group_by(Genus, State) %>% summarise(Count = n()) %>%
  ggplot(aes(reorder(Genus, Count, FUN = sum), Count, fill = State)) +
  geom_col() +
  coord_flip() +
  ggtitle("Number of sightings of each genus") +
  xlab("Genus") +
  ylim(c(0, 1800)) +
  theme(axis.title = element_text(size = 16),
        plot.title = element_text(size = 20))
```



```{r}
bees %>% group_by(State) %>% summarise(Unique = n_distinct(Genus)) %>%
  ggplot(aes(reorder(State, Unique, FUN = function(x)sum(x)), Unique)) +
  geom_col(fill = "#0099FF") +
  geom_text(aes(label = Unique), size = 6, hjust = -0.1) +
  coord_flip() +
  ggtitle("Genus diversity of bees by state") +
  xlab("State") +
  ylab("Number of unique genus per state") +
  ylim(c(0, 34)) +
  theme(axis.title = element_text(size = 16),
        plot.title = element_text(size = 20))
```

# Question: Is the distribution of the number of unique sightings equal over month and state?

```{r}
genus_state_month <- bees %>% group_by(Genus, State, Month) %>% summarise(Unique = n_distinct(Genus)) %>% 
  drop_na()
genus_state_month_barplot <- genus_state_month %>%
  ggplot(aes(reorder(State, Unique, FUN = function(x)sum(x)), Unique)) +
  geom_col(aes(fill = Month)) +
  ggtitle("Number of unique genus sighted",
          subtitle = "From May to September") +
  coord_flip() +
  xlab("State") +
  ylab("Count") +
  theme(axis.title = element_text(size = 16),
        plot.title = element_text(size = 20),
        axis.text = element_text(size = 14))
genus_state_month_barplot

# ggsave("genus_state_month_barplot.png", plot = genus_state_month_barplot)

# ggsave("genus_state_month_barplot.png", plot = genus_state_month_barplot,
#        path = here("Assignments", "Assignment3", "figures/genus_state_month_barplot.png"))

```

```{r}
# genus_state_month <- bees %>% group_by(State, Month) %>% summarise(Unique = n_distinct(Genus)) %>% 
#   drop_na()
genus_state_month_mosaicplot <-genus_state_month %>%
  ggplot() +
  geom_mosaic(aes(weight = Unique, x = product(State), fill = Month)) +
  ggtitle("Proportion of unique genus sighted",
          subtitle = "From May to September") +
  xlab("State") +
  ylab("Month") +
  coord_flip() +
  theme(axis.title = element_text(size = 16),
        plot.title = element_text(size = 20),
        axis.text = element_text(size = 14))
genus_state_month_mosaicplot

# ggsave("genus_state_month_mosaicplot.png", plot = genus_state_month_mosaicplot)
```



```{r}
ct_gsm<- genus_state_month %>% group_by(State, Month) %>% summarise(Unique = n_distinct(Genus)) %>% 
  spread(key = Month, value = Unique)
ct_gsm
```

```{r}
ungroup(ct_gsm) %>%
  select(-State) %>% chisq.test()
```

```{r}
ungroup(ct_gsm) %>%
filter(State != c("Wisconsin"))%>%
  select(-State) %>% chisq.test()
```

```{r}
ungroup(ct_gsm) %>%
filter(State %nin% c("Wisconsin", "Illinois")) %>%
  select(-State) %>% chisq.test()
```

```{r}
species_state_month <- bees %>% group_by(Species, State, Month) %>% summarise(Unique = n_distinct(Species)) %>% 
  drop_na()
species_state_month_bargraph <- species_state_month %>%
  ggplot(aes(reorder(State, Unique, FUN = function(x)sum(x)), Unique)) +
  geom_col(aes(fill = Month)) +
  coord_flip() +
  ggtitle("Number of unique species sighted",
          "From May to September") +
  xlab("State") +
  theme(axis.title = element_text(size = 16),
        plot.title = element_text(size = 20),
        axis.text = element_text(size = 14))
species_state_month_bargraph

# ggsave("species_state_month_bargraph.png", species_state_month_bargraph)
```

```{r}
species_state_month_mosaicplot <- species_state_month %>%
  ggplot() +
  geom_mosaic(aes(weight = Unique, x = product( State  )   , fill = Month)) +
  coord_flip() +
  ggtitle("Proportion of unique species sighted per month",
          "From May to September") +
  xlab("State") +
  ylab("Month") +
  theme(axis.title = element_text(size = 16),
        plot.title = element_text(size = 20),
        axis.text = element_text(size = 14))
species_state_month_mosaicplot

# ggsave("species_state_month_mosaicplot.png", species_state_month_mosaicplot)
```

```{r}
ct_ssm<- species_state_month %>% group_by(State, Month) %>% summarise(Unique = n_distinct(Species)) %>% 
  spread(key = Month, value = Unique)
ct_ssm
```

```{r}
ungroup(ct_ssm) %>%
  select(-State) %>% chisq.test()
```

```{r}
ungroup(ct_ssm) %>%
filter(State != c("Wisconsin"))%>%
  select(-State) %>% chisq.test()
```

```{r}
ungroup(ct_ssm) %>%
filter(State %nin% c("Wisconsin", "Illinois")) %>%
  select(-State) %>% chisq.test()
```

```{r}
top10_genus <- bees %>% group_by(Genus) %>% summarise(Count = n()) %>% top_n(10, Count) %>% arrange(desc(Count)) %>% select(Genus) %>% .$Genus

state_month_genus_count <- bees %>% group_by(State, Month, Genus) %>% summarise(Count = n())
```


```{r}
state_month_genus_count_facetplot <- state_month_genus_count %>% drop_na %>% filter(Genus %in% top10_genus) %>% 
  ggplot(aes(Month, Count)) +
  geom_col(fill = "#0099FF") +
  ggtitle("Diversity of top ten genus by state",
          "From May to September")+
  facet_grid(State~reorder(Genus, Count)) +
  theme(axis.title = element_text(size = 16),
        plot.title = element_text(size = 20),
        axis.text = element_text(size = 14),
        axis.text.x = element_text(angle = 90))
state_month_genus_count_facetplot

ggsave("state_month_genus_count_facetplot.png", state_month_genus_count_facetplot, height = 8, width = 14)
```

```{r}
top10_species <- bees %>% group_by(Species) %>% summarise(Count = n()) %>% top_n(10, Count) %>% arrange(desc(Count)) %>% select(Species) %>% .$Species

state_month_species_count <- bees %>% group_by(State, Month, Species) %>% summarise(Count = n())

state_month_species_count_facetplot <- state_month_species_count %>% drop_na %>% filter(Species %in% top10_species) %>% 
  ggplot(aes(Month, Count)) +
  geom_col(fill = "#0099FF") +
  facet_grid(State~Species) +
  theme(axis.title = element_text(size = 16),
        plot.title = element_text(size = 20),
        axis.text = element_text(size = 14),
        axis.text.x = element_text(angle = 90))
state_month_species_count_facetplot
```



```{r}
species_counts <- bees %>% group_by(Species) %>%
  summarise(Count = n(),
            Unique = n_distinct(Species))

species_counts %>% top_n(10, Count) %>% 
  ggplot(aes(reorder(Species, Count), Count)) +
  geom_col(fill = "#0099FF")  +
  geom_text(aes(label = Count, hjust = -0.1)) +
  coord_flip() +
  ggtitle("Number of sightings of each species") +
  xlab("Species") +
  # ylim(c(0, 1800)) +
  theme(axis.title = element_text(size = 20),
        plot.title = element_text(size = 20))
```

```{r}
bees %>% group_by(Species, State) %>% summarise(Count = n(),
                                                Unique = n_distinct(Species))
```



```{r}
bees %>% group_by(State) %>% summarise(Unique = n_distinct(Species)) %>%
  ggplot(aes(reorder(State, Unique), Unique)) +
  geom_col(fill = "#0099FF") +
  coord_flip() +
  ggtitle("Number of unique species") +
  xlab("State") +
  theme(axis.title = element_text(size = 20),
        plot.title = element_text(size = 20))
```

```{r}
bees %>% group_by(State) %>% summarise(Unique = n_distinct(Species)) %>%
  ggplot(aes(reorder(State, Unique), Unique)) +
  geom_col() +
  coord_flip() +
  ggtitle("Number of unique species") +
  xlab("State") +
  theme(axis.title = element_text(size = 20),
        plot.title = element_text(size = 20))
```




```{r}
genus_species_state_habitat <- bees %>% group_by(Genus, Species, State, Habitat) %>% 
  summarise(Count = n())

genus_species_state_habitat
```


```{r}
state_month_genus_species <- bees %>% group_by(State, Month, Genus, Species) %>% 
  summarise(Count = n(),
            `Num. Unique` = n_distinct(Species))

state_month_genus_species
```

```{r}
fig_state_species_month_strong <- state_month_genus_species %>% filter(Species %in% top10_species) %>% drop_na() %>% filter(State %in% strong_states) %>% 
  ggplot(aes(Month, Count)) +
  geom_col() +
  facet_grid(State~Species) +
  theme_minimal() +
  ggtitle("Investigating the top ten most recorded species",
          subtitle = "Across the most prevalent states") +
  theme(axis.text.x = element_text(angle = 90))
  

fig_state_species_month_strong
  
ggsave(filename = "fig_state_species_month_strong.jpeg",
       plot = fig_state_species_month_strong,
       path = here("Assignments", "Assignment3", "figures", "fig_state_species_month_strong.jpeg"),
       dpi = 300)
```